name: Generate Docs
on:
  push:
    branches: [ main ]

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Rebuild docs
        run: make clean-docs \
             make docs \
             git add -f $(make docs-list) \
             git -c usser.email="actions@github.com" -c user.name="GitHub Actions" commit -m "Autogenerate Docs" --author "stoey <stoey@users.noreply.github.com>" \
             git push --set-upstream oriigin HEAD:main

