name: Generate Docs
on:
  push:
    branches: [ main ]

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Rebuild docs
        run: make clean-docs
        run: make docs
        run: git add -f $(make docs-list)
        run: git -c usser.email="actions@github.com" -c user.name="GitHub Actions" commit -m "Autogenerate Docs" --author "stoey <stoey@users.noreply.github.com>"
        run: git push --set-upstream oriigin HEAD:main

